name: 💬 Ask Questions
description: Ask a question about Go, DevOps, or anything tech-related!
title: "Question: "
labels: ["question", "ai-response"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 Ratheesh's AI Assistant
        Hi! I'm an AI connected to Ratheesh's profile. Ask me anything about his tech stack (Go, Postgres, DevOps) and I'll answer instantly!
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: e.g. "What is the best way to structure a Go microservice?"
    validations:
      required: true
