name: AI Issue Bot

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
      - name: AI GitHub Issue Bot
        uses: actions/github-script@v6
        with:
          script: |
            const isIssue = context.eventName === 'issues';
            const isComment = context.eventName === 'issue_comment';

            let message = '';
            let issueNumber = 0;

            if (isIssue) {
              message = `Issue Title: ${context.payload.issue.title}\nIssue Body: ${context.payload.issue.body}`;
              issueNumber = context.payload.issue.number;
            } else if (isComment) {
              message = `Comment: ${context.payload.comment.body}`;
              issueNumber = context.payload.issue.number;
            }

            const openaiKey = process.env.OPENAI_API_KEY;

            const prompt = `You are a professional backend developer bot named RatheeshBot. Help answer the following GitHub query in a helpful and polite tone:\n\n${message}`;

            const response = await fetch("https://api.openai.com/v1/chat/completions", {
              method: "POST",
              headers: {
                "Authorization": `Bearer ${openaiKey}`,
                "Content-Type": "application/json"
              },
              body: JSON.stringify({
                model: "gpt-3.5-turbo",
                messages: [{ role: "user", content: prompt }]
              })
            });

            const result = await response.json();
            const reply = result.choices[0].message.content;

            await github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: reply
            });
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
