name: Profile Bot Response

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Auto Response Bot
        uses: actions/github-script@v6
        with:
          script: |
            const isIssue = context.eventName === 'issues';
            const isComment = context.eventName === 'issue_comment';

            let triggerText = '';
            let issueNumber = 0;

            if (isIssue) {
              triggerText = context.payload.issue.title.toLowerCase() + ' ' + context.payload.issue.body.toLowerCase();
              issueNumber = context.payload.issue.number;
            } else if (isComment) {
              triggerText = context.payload.comment.body.toLowerCase();
              issueNumber = context.payload.issue.number;
            }

            let response = '';

            if (triggerText.includes('experience') || triggerText.includes('skills')) {
              response = `👋 **Hi there! I'm Ratheesh Kumar**

🔧 Backend Developer with strong skills in:

- Golang 🐹  
- PostgreSQL 🐘  
- Microservices ⚙️  
- Docker & Kubernetes 🐳  
- System Design & Optimization 💡

Let me know if you'd like to learn more about any of these!`;
            }

            else if (triggerText.includes('golang') || triggerText.includes('go')) {
              response = `🐹 **GoLang Insights**

- Go is my primary backend language.
- I specialize in goroutines, channels, REST APIs, and performance tuning.
- Ask me anything about concurrency, interfaces, or idiomatic Go patterns!`;
            }

            else if (triggerText.includes('postgres') || triggerText.includes('postgresql')) {
              response = `🐘 **PostgreSQL Expertise**

- Experienced in schema design, indexes, joins, views, and stored procedures.
- I’ve optimized queries for high-traffic backend services.
- Feel free to ask how I use it with Go!`;
            }

            else if (triggerText.includes('projects') || triggerText.includes('work')) {
              response = `🚀 **My Top Projects**

- [Opti Cutter Final](https://github.com/ratheeshkumar25/opti_cutter_final)
- [Restaurant Management](https://github.com/ratheeshkumar25/restaurantmgt)
- [Blog CRUD](https://github.com/ratheeshkumar25/blog-crud)

Let me know if you'd like to dive deeper into any one!`;
            }

            else if (triggerText.includes('contact') || triggerText.includes('connect')) {
              response = `📬 **Contact Me**

- 📧 Email: [ratheeshgopinadhkumar@gmail.com](mailto:ratheeshgopinadhkumar@gmail.com)
- 💼 LinkedIn: [Ratheesh G Kumar](https://www.linkedin.com/in/ratheesh-gopinadh-kumar-b5191166)
- 💻 GitHub: [@ratheeshkumar25](https://github.com/ratheeshkumar25)`;
            }

            else {
              response = `🤖 **Hi! I'm Ratheesh's Profile Bot**

Type your question using keywords like:
- "experience"
- "Golang"
- "PostgreSQL"
- "projects"
- "contact"

I'll reply automatically with relevant info! 🚀`;
            }

            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: response
            });
